# Generated by Django 4.0.3 on 2022-04-07 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_survey_created_survey_end_time_survey_start_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='choices',
        ),
    ]
